### ISSUE TITLE
Scoreboard and display issues

### ISSUE THREAD

**Issue by Edrow-6** [Dart2112/AFKPlusPrefix#1]
The plugin makes the scoreboard and the "setdisplay" of the "scoreboard" command disappear.

**Comment by helpimnotdrowning** [comment]
Having same problem, am on paper 1.16.3

**Comment by Yoncuu** [comment]
Playing on Spigot 1.16.5 and still hasn't been addressed. Turns out it's even worse. I have different /trigger commands for several data packs such as Timber, Coordinates HUD or MultiplayerSleep, and once AFKPusPrefix is installed, you are no longer able to use the /trigger command. I kept getting the message: You cannot trigger this objective yet!
I had also set a scoreboard to show the hearts within the TAB window, and they disappeared as well. 

AFKPlus by itself is a great plugin, I just wish there was a way to let other people (particularly those who connected after you had already gone AFK and as such did not get to receive the AFK notification) know that you are AFK. 
Making this add-on compatible with other scoreboards would make the plugin even miles better, I hope it can be taken into account.

**Comment by Dart2112** [comment]
> Playing on Spigot 1.16.5 and still hasn't been addressed. Turns out it's even worse. I have different /trigger commands for several data packs such as Timber, Coordinates HUD or MultiplayerSleep, and once AFKPusPrefix is installed, you are no longer able to use the /trigger command. I kept getting the message: You cannot trigger this objective yet!
> I had also set a scoreboard to show the hearts within the TAB window, and they disappeared as well.
> 
> AFKPlus by itself is a great plugin, I just wish there was a way to let other people (particularly those who connected after you had already gone AFK and as such did not get to receive the AFK notification) know that you are AFK.
> Making this add-on compatible with other scoreboards would make the plugin even miles better, I hope it can be taken into account.

It's not something that can be taken into account. The scoreboard system in Spigot doesn't seem to allow what AFKPlusPrefix requires alongside other scoreboards. I'll try to do some more investigating but I doubt this is fixable. 

These incompatibilities are exactly why this plugin is an add on and not a part of the core plugin

**Comment by Yoncuu** [comment]
> > Playing on Spigot 1.16.5 and still hasn't been addressed. Turns out it's even worse. I have different /trigger commands for several data packs such as Timber, Coordinates HUD or MultiplayerSleep, and once AFKPusPrefix is installed, you are no longer able to use the /trigger command. I kept getting the message: You cannot trigger this objective yet!
> > I had also set a scoreboard to show the hearts within the TAB window, and they disappeared as well.
> > AFKPlus by itself is a great plugin, I just wish there was a way to let other people (particularly those who connected after you had already gone AFK and as such did not get to receive the AFK notification) know that you are AFK.
> > Making this add-on compatible with other scoreboards would make the plugin even miles better, I hope it can be taken into account.
> 
> It's not something that can be taken into account. The scoreboard system in Spigot doesn't seem to allow what AFKPlusPrefix requires alongside other scoreboards. I'll try to do some more investigating but I doubt this is fixable.
> 
> These incompatibilities are exactly why this plugin is an add on and not a part of the core plugin

Alright, no problems bro. I just wanted to know if there was a possibility. Thank you either way.

**Comment by Dart2112** [comment]
So after some investigation, it seems that I was right that the plugin cannot operate without interfering with other scoreboard based plugins. But it could be a little more compatible. So I'm pushing an update that should make it a little better, to be clear this will not fix all issues but it should make it compatible for players who aren't AFK. AFK players may have their scoreboard based functions break depending on how the other plugins work.

**Comment by Yoncuu** [comment]
I just downloaded it and it seems to be working flawlessly so far with the scoreboard based datapacks I have installed in my server (MP Sleep, Timber, Graves, Coordinates HUD and Nether Portal Coords). You can even execute the trigger commands whenever AFK, and the prefix also shows alongside the hearts established from the health scoreboard objective. Whatever you did, great job dude. I will keep informing on any other events.
