### ISSUE TITLE
Prefix not showing in tab

### ISSUE THREAD

**Issue by davigamer987** [Dart2112/AFKPlusPrefix#4]
i use this tab plugin https://github.com/NEZNAMY/TAB
It doesn't show afk

**Comment by Dart2112** [comment]
I'll have a look and see what I can do. But it's unlikely that two plugins modifying tab lists are going to work together

**Comment by Dart2112** [comment]
Having a look at how that plugin does prefixes, its never going to work with AFKPlus Prefix
