### ISSUE TITLE
Player leave while AFK bug

### ISSUE THREAD

**Issue by DaenenTDD** [Dart2112/AFKPlusPrefix#5]
If a player leaves while AFK, when they join back their status is stuck until they manually set their status as AFK and then remove it, or automatically get set as AFK and remove it.

Maybe add a check to remove AFK status when they join the server?

**Comment by Dart2112** [comment]
This isn't an issue with this plugin but rather an issue with the main AFKPlus plugin. I'll recreate the issue there and tag you when I start validating it

**Comment by Dart2112** [comment]
The code currently deployed in AFKPlus does stop AFK for players joining a server. Please open an issue on the AFKPlus GitHub if this issue still persists
