### ISSUE TITLE
Installing Problems

### ISSUE THREAD

**Issue by Jonnyduma** [Dart2112/AFKPlusPrefix#8]
I Don't get it. I put this File into the Server Plugins folder. Nothing happens. 
I Restarted the Server and extracted the Files. Neither helped. Yes I Installed AFK+ first. And this is working. Only the Add-on isn't working.
Please help :)

**Comment by Dart2112** [comment]
https://github.com/Dart2112/AFKPlusPrefix/releases/latest

Make sure you are using the jar file from the releases page. It sounds like you're attempting to just place the code in the server which will not work. You need the compiled jar

**Comment by Jonnyduma** [comment]
you are absolutly right. Sorry hehe
